spring:
  application:
    name: BankManager

  datasource:
    url: jdbc:mysql://82.156.214.214/DBBS
    username: root
    password: aptx&4869
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083

app:
  # 备份配置
  backup:
    # 备份数据库
    db: "DBBS"
    # 备份文件存储目录
    dir: "/home/ubuntu/backupDatabase"
    # 备份文件最多保留时间。如，5分钟：5m、12小时：12h、1天：1d
    max-age: 1d